name: Build-and-publish

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      CIBW_BEFORE_ALL_LINUX: "curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y"
      CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
      CIBW_SKIP: "pp39-* *-musllinux_*"
      
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
      
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel wheel setuptools setuptools-rust
        
      - name: Update packages
        run : python -m pip install --upgrade cibuildwheel wheel setuptools setuptools-rust
        
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: ./wheelhouse/*.whl
  
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: actions/setup-python@v3

      - name: Build sdist
        run: |
          python -m pip install setuptools-rust setuptools
          python setup.py sdist
          
      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/*.tar.gz
  
  publish_wheel:
    needs: [build_wheels]
    name: Upload wheel to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheel
          path: ./wheelhouse

      - uses: actions/setup-python@v3

      - name: Install twine
        run: |
          python -m pip install --upgrade twine

      - name: Upload to TestPyPI
        run: |
          python3 -m twine upload --skip-existing ./wheelhouse/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi
          
  publish_sdist:
    needs: [build_sdist]
    name: Upload sdist to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sdist
          path: dist/

      - uses: actions/setup-python@v3

      - name: Install twine
        run: |
          python -m pip install --upgrade twine

      - name: Upload to TestPyPI
        run: |
          python3 -m twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi
